--bind "alt-e:execute($EDITOR {})"
--bind "alt-o:execute-silent(open {})"
--bind alt-a:select-all
--bind alt-d:deselect-all
--bind btab:up
--bind ctrl-/:toggle-preview
--bind ctrl-space:toggle
--bind ctrl-z:ignore
--bind shift-down:toggle+down
--bind shift-left:preview-up
--bind shift-right:preview-down
--bind shift-up:toggle+up
--bind tab:down
--border
--color light
--cycle
--exact
--no-height
--preview-window 60%:wrap
--reverse
--tabstop 2
--wrap
