---
- import_tasks: git.yml
  when: (_git_ or _all_) and not _is_win_

- import_tasks: win_git.yml
  when: (_git_ or _all_) and _is_win_

#

- import_tasks: sync.yml
  when: not _is_win_

- import_tasks: win_sync.yml
  when: _is_win_

#

- import_tasks: template.yml
  when: not _is_win_

- import_tasks: win_template.yml
  when: _is_win_

#

# - import_tasks: command.yml
#   when: not _is_win_

# - import_tasks: win_command.yml
#   when: _is_win_
