---
brew_packages:
  - aha
  - asciiquarium
  - autossh
  - awk
  - bandwhich
  - bash
  - bat
  - bind
  - btop
  - cmatrix
  - coreutils
  - cowsay
  - curl
  - dash
  - diffutils
  - dog
  - dust
  - exa
  - fd
  - figlet
  - findutils
  - fzf
  - gettext
  - gitui
  - glib-openssl
  - gnu-getopt
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnupg
  - grep
  - htop
  - hyperfine
  - iperf3
  - jandedobbeleer/oh-my-posh/oh-my-posh
  - jid
  - jless
  - jq
  - lazygit
  - less
  - lolcat
  - lsof
  - man2html
  - moreutils
  - mosh
  - mpv
  - ms-jpq/sad/sad
  - muesli/tap/duf
  - ncdu
  - neofetch
  - neovim
  - nmap
  - nyancat
  - openssh
  - pastel
  - pipes-sh
  - pstree
  - pv
  - ripgrep
  - rlwrap
  - rsync
  - sl
  - socat
  - termshark
  - tmux
  - tokei
  - trash
  - tree
  - universal-ctags
  - watch
  - watchexec
  - wget
  - xsv

target_files:
  - src: "home/"
    dest: "~/"

target_templates: []

target_links:
  - src: "{{ '/opt/homebrew' if ansible_architecture == 'arm64' else '/usr/local' }}/bin/dash"
    dest: "~/.local/bin/sh"

target_archives: []
