#!/usr/bin/env bash

##########################
# OSC 52 Escape Sequence #
##########################

DATA="$(base64 --wrap=0)"

case "$TERM" in
  xterm-256color)
    ENCODING="\e]52;c;%s\07"
    ;;
  screen-256color)
    ENCODING="\ePtmux;\e\e]52;c;%s\a\e\\"
    ;;
  *)
    echo "unrecognized TERM - $TERM"
    return 1
esac

ENCODED="$(printf "$ENCODING" "$DATA")"

echo -ne "$ENCODED"
