#!/usr/bin/env bash

##########################
# OSC 52 Escape Sequence #
##########################

DATA="$(base64 --wrap=0)"

if [[ -v "TMUX" ]]
then
  ENCODING="\ePtmux;\e\e]52;c;%s\a\e\\"
else
  ENCODING="\e]52;c;%s\07"
fi

ENCODED="$(printf "$ENCODING" "$DATA")"

echo -ne "$ENCODED"
