---
- hosts: localhost
  connection: local
  vars:
    all: True

  tasks:
    - assert:
        that: ansible_distribution == 'Ubuntu'

    - import_role:
        name: unix
    - import_role:
        name: ubuntu
