---
- hosts: localhost
  connection: local
  vars:
    all: True
    ansible_user: root

  tasks:
    - assert:
        that: ansible_distribution == 'Ubuntu'

    - import_role:
        name: _unix
    - import_role:
        name: ubuntu
