---

- hosts: localhost
  connection: local

  vars:

  tasks:
    - assert:
        that: ansible_distribution == 'MacOSX'

    - import_role:
        name: _unix
    - import_role:
        name: macos
