#!/usr/bin/env -S -- bash

if [ "$#" -eq 0 ]
then
  export -- DOCKER_HOST='unix:///var/run/docker.sock'
else
  export -- DOCKER_HOST="tcp://$1:${2:-2375}"
fi
printf -- '%s\n' "DOCKER_HOST=$DOCKER_HOST"

