#!/usr/bin/env bash

if [[ $# -ne 0 ]]
then
  if [[ -v TMUX ]]
  then
    :
  else
    tmux new-session -A -s "$*"
  fi
else
  session="$(tmux list-sessions -F '#{session_name}' | fzf -0 -1)"
  if [[ $? -ne 130 ]]
  then
    if [[ -v TMUX ]]
    then
      tmux switch -t "$session"
    else
      tmux new-session -A -s "${session:-"owo"}"
    fi
  fi
fi
