$Env:PAGER = 'less'
$Env:LESS = @(
  '--quit-on-intr'
  '--quit-if-one-screen'
  '--mouse'
  '--RAW-CONTROL-CHARS'
  '--tilde'
  '--tabs=2'
  '--QUIET'
  '--ignore-case'
  '--no-histdups'
) | Join-String -Separator ' '
$Env:LESSHISTFILE = Join-Path -- ($IsWindows ? $Env:TMP : $Env:XDG_CACHE_HOME) 'less-hist'

$Env:TIME_STYLE = 'long-iso'
$Env:EDITOR = 'nvim'
$Env:MANPAGER = 'nvim +Man!'
