---
- name: set windows path sep
  ansible.builtin.set_fact:
    backslash: \

- name: set windows PATH
  ansible.builtin.set_fact:
    posix_path: >-
      /usr/bin:{{ ansible_env.Path | split(';') | map('regex_replace', '^' ~ ansible_env.SystemDrive, '/' ~ ansible_env.SystemDrive.strip(':').lower()) | map('replace', backslash, '/') | join(':') }}

- name: check git repo exists
  loop: "{{ git_repos }}"
  ansible.windows.win_stat:
    path: "{{ item.dst }}"
  register: __git_repos

- name: clone git repos
  loop: "{{ git_repos }}"
  loop_control:
    index_var: index
  when: not __git_repos.results[index].stat.exists
  ansible.windows.win_command:
    argv:
      - "{{ ansible_env.SystemDrive ~ '/msys64/usr/bin/env.exe' }}"
      - "PATH={{ posix_path }}"
      - git
      - clone
      - --recurse-submodules
      - --depth=1
      - --shallow-submodules
      - --
      - "{{ item.src }}"
      - "{{ item.dst }}"

- name: pull git repos
  loop: "{{ git_repos }}"
  loop_control:
    index_var: index
  when: __git_repos.results[index].stat.exists
  ansible.windows.win_command:
    chdir: "{{ item.dst }}"
    argv:
      - "{{ ansible_env.SystemDrive ~ '/msys64/usr/bin/env.exe' }}"
      - "PATH={{ posix_path }}"
      - git
      - pull
      - --recurse-submodules
      - --no-tags
      - --
      - "{{ item.src }}"
