protocol mailto
action launch --type=os-window -- /opt/homebrew/bin/zsh -l -c 'aerc "$1"' _ ${URL}

protocol file
mime inode/directory
action launch --type=os-window -- /opt/homebrew/bin/zsh -l -c '"$HOME/.local/libexec/yazi.sh" -- "$1"' _ ${FILE_PATH}

protocol file
action launch --type=os-window -- /opt/homebrew/bin/zsh -l -c 'nvim -- "$1"' _ ${FILE_PATH}
