protocol mailto
action launch --type=os-window -- /opt/homebrew/bin/zsh -i -c 'aerc "$1"' _ ${URL}

protocol file
mime inode/directory
action launch --type=os-window -- /opt/homebrew/bin/zsh -i -c '"$HOME/.local/libexec/yazi.sh" -- "$1"' _ ${FILE_PATH}

protocol file
action launch --type=os-window -- /opt/homebrew/bin/zsh -i -c 'nvim +"$2" -- "$1"' _ ${FILE_PATH} ${LINE}
