protocol file
mime inode/directory
action launch --type=window --cwd=current --copy-env -- /opt/homebrew/bin/zsh -c '"$HOME/.local/libexec/yazi.sh" -- "$1"' _ ${FILE_PATH}

protocol file
fragment_matches .+
action launch --type=window --cwd=current --copy-env -- nvim +${FRAGMENT} -- ${FILE_PATH}

protocol file
action launch --type=window --cwd=current --copy-env -- nvim -- ${FILE_PATH}
