#!/usr/bin/env bash

ta() {
  local session="$*"
  if [[ $# -ne 0 ]]
  then
    if [[ -v TMUX ]]
    then
      tmux new-session -d -s "$session"
      tmux switch -t "$session"
    else
      tmux new-session -A -s "$session"
    fi
  else
    session="$(tmux list-sessions -F '#{session_name}' | fzf -0 -1)"
    if [[ $? -ne 130 ]]
    then
      if [[ -v TMUX ]]
      then
        tmux switch -t "$session"
      else
        tmux new-session -A -s "${session:-'owo'}"
      fi
    fi
  fi
}
