#!/usr/bin/env -S -- bash

ta() {
  local session="$*"
  if (($#)); then
    if [[ -v TMUX ]]; then
      tmux new-session -d -c "$HOME" -s "$session"
      tmux switch -t "$session"
    else
      tmux new-session -A -c "$HOME" -s "$session"
    fi
  else
    session="$(tmux list-sessions -F '#{session_name}' | fzf -0 -1)"
    if [[ $? -ne 130 ]]; then
      if [[ -v TMUX ]]; then
        tmux switch -t "$session"
      else
        tmux new-session -A -c "$HOME" -s "${session:-owo}"
      fi
    fi
  fi
}
