#!/usr/bin/env -S -- bash

taa() {
  local session=
  session="$(tmux list-sessions -F '#{session_name}' | fzf -0)"
  if [[ -v TMUX ]]; then
    tmux switch -t "$session"
  else
    tmux new-session -t "$session"
  fi
}
