# https://man.archlinux.org/man/aerc-accounts.5.en

check-mail        = 5m

[<account>]
check-mail-cmd    = ~/.config/aerc/hooks/check-mail.sh <account>
address-book-cmd  = abook <account> %s
source            = maildir://~/.local/share/maildir/<account>
outgoing          = smtp+xoauth2://<email+uri-escape>@<smtp-server>
source-cred-cmd = "~/.local/opt/isync/oauth.sh -- ~/.local/state/isync/<email>.oauth.gpg"
outgoing-cred-cmd = "~/.local/opt/isync/oauth.sh -- ~/.local/state/isync/<email>.oauth.gpg"
from              = "(whoami) <email>"
# copy-to           = "Sent Items"
postpone          = "Drafts"
folders-exclude   = "Calendar,Contacts,Conversation History,Journal,Notes,Outbox,Tasks"
folders-sort      = "Inbox,Sent Items,Drafts,Trash"
folder-map        = ~/.config/aerc/remaps/outlook.conf
