check-mail        = 5m

[<account>]
check-mail-cmd    = ~/.config/aerc/hooks/check-mail.sh <account>
source            = maildir://~/.local/share/maildir/<account>
outgoing          = smtp+xoauth2://<email+uri-escape>@<smtp-server>
outgoing-cred-cmd = "~/.local/opt/isync/oauth.sh -- ~/.local/state/isync/<email>.oauth.gpg"
from              = "(whoami) <email>"
copy-to           = "Sent Items"
folders-exclude   = "Calendar,Contacts,Conversation History,Journal,Notes,Tasks"
folders-sort      = "Inbox,Sent Items"
