# https://man.archlinux.org/man/aerc-accounts.5.en

# check-mail         = 5m
check-mail-timeout = 30s

[<account>]
check-mail-cmd     = ~/.config/aerc/hooks/check-mail.sh <account>
address-book-cmd   = abook <account> %s
source             = maildir://~/.local/share/maildir/<account>
maildir-store      = ~/.local/share/maildir/<account>
outgoing           = smtp+xoauth2://<email+uri-escape>@<smtp-server>
source-cred-cmd    = "~/.local/opt/isync/oauth.sh -- ~/.local/state/isync/<email>.oauth.gpg"
outgoing-cred-cmd  = "~/.local/opt/isync/oauth.sh -- ~/.local/state/isync/<email>.oauth.gpg"
from               = "(whoami) <email>"
aliases            =
# copy-to           = "Sent Items"
postpone           = "草稿"
# folders-exclude    = "~日历"
folders-sort       = "收件箱,草稿,发件箱,已发送邮件,存档,已删除邮件,垃圾邮件"
folder-map         = ~/.config/aerc/remaps/outlook.conf
