# https://man.archlinux.org/man/aerc-config.5.en
# https://man.sr.ht/~rjarry/aerc

[general]

default-menu-cmd=fzf --multi
default-save-path=~/Downloads
disable-ipc-mailto=true
disable-ipc-mbox=true
enable-osc8=true
enable-quake-mode=true
pgp-provider=gpg
use-terminal-pinentry=true

[ui]

timestamp-format=2006-01-02
this-day-time-format=15:04
this-week-time-format=01-02
this-year-time-format=01-02

completion-delay=0ms
dirlist-delay=0ms
dirlist-tree=true
fuzzy-complete=true
mouse-enabled=true
msglist-scroll-offset=6
new-message-bell=false
# sort=-r read -r date

force-client-threads=true
show-thread-context=true
sort-thread-siblings=true
threading-enabled=true

# reverse-thread-order=true
# thread-prefix-tip=""
# thread-prefix-indent=""

icon-attachment="󰁦"
icon-deleted=""
icon-draft="󰙏"
icon-flagged="󰈻"
icon-marked="󰍎"
icon-new="󰏌"
icon-old="󰏌"
icon-replied=""
pinned-tab-marker="󰐃"
spinner=",,,"

spinner-interval=166ms
styleset-name=default

[statusline]

display-mode=icon

[viewer]

header-layout=From|To,Cc,Date,Subject
pager=less
# show-headers=true

alternatives=text/html,text/plain
always-show-mime=true

[compose]

reply-to-self=false
header-layout=From|To,Cc,Subject
file-picker-cmd=fzf --multi --query=%s
address-book-cmd=abook %s

[multipart-converters]

text/html=pandoc --standalone --embed-resources --eol lf --read gfm --write html

[filters]

.headers=colourize.sh
message/delivery-status=colourize.sh
message/rfc822=colourize.sh

text/calendar=calendar
text/html=html.sh
text/plain=colourize.sh

application/pdf=pdf.sh
application/zip=zip.sh
image/*=img.sh
text/markdown=markdown.sh

# text/*=bat --force-colorization --paging=never --style=plain --file-name="$AERC_FILENAME" -- -

[openers]

[hooks]

flag-changed=~/.config/aerc/hooks/flag-changed.sh
mail-added=~/.config/aerc/hooks/flag-changed.sh
mail-deleted=~/.config/aerc/hooks/flag-changed.sh

# mail-sent=
# mail-received=

[templates]
forwards=x-forward.gotmpl
quoted-reply=x-quoted-reply.gotmpl
