#!/usr/bin/with-contenv bash

set -eu
set -o pipefail

export PATH="/usr/local/bin:$PATH"

THEME="$(cat /etc/ttyd/theme.json)"

/usr/local/bin/ttyd --port=8080 -t "theme=$THEME" -t "fontSize=$FONT_SIZE" /usr/bin/zsh
