---
packages:
  - git
  - zsh

target_files:
  - src: "home/"
    dst: "~/"

target_touches:
  - "~/.ssh/config"
  - "{{ _xdg_conf_home_ }}/git/config"
  - "{{ _xdg_cache_home_ }}/zz"

git_conf:
  include.path: user_config

target_lines:
  - file: "~/.ssh/config"
    line: "Include ~/.config/ssh/*.conf"
