reporting: "on"

git:
  paging:
    pager: delta --paging=never

gui:
  scrollHeight: 1
  theme:
    lightTheme: True
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
