[input]
prepend_keymap = [{ on = "<Esc>", run = "close" }]

[[mgr.prepend_keymap]]
on  = "R"
run = "refresh"

[[mgr.prepend_keymap]]
on  = ["e", "x"]
run = "shell -- chmod -- +x %s"
[[mgr.prepend_keymap]]
on  = ["e", "X"]
run = "shell -- chmod -- -x %s"

[[mgr.prepend_keymap]]
desc = "Copy the relative path"
on   = ["c", "r"]
run  = "shell -- ~/.config/yazi/libexec/copy-relative.sh %h"

[[mgr.prepend_keymap]]
desc = "Symlink selected paths"
on   = ["s", "l"]
run  = "shell -- ~/.config/yazi/libexec/symlink-relative.sh %s"
