theme = "cls"

[editor]
auto-format               = false
bufferline                = "never"
color-modes               = true
completion-replace        = true
completion-timeout        = 5
completion-trigger-len    = 1
cursorline                = true
end-of-line-diagnostics   = "hint"
idle-timeout              = 50
popup-border              = "all"
preview-completion-insert = false
rainbow-brackets          = true
trim-trailing-whitespace  = true
true-color                = true

[editor.auto-save]
after-delay.enable  = true
after-delay.timeout = 1000
focus-lost          = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render      = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[editor.lsp]
display-inlay-hints                = false
display-messages                   = true
display-progress-messages          = true
goto-reference-include-declaration = false

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["workspace-diagnostics"]
right = [
  "diagnostics",
  "file-encoding",
  "file-indent-style",
  "position",
  "position-percentage",
]

[editor.word-completion]
trigger-length = 1

[keys.insert]
A-left  = ["move_prev_word_end", "move_char_left", "move_char_right"]
A-right = ["move_next_word_start", "move_char_right"]
C-a     = "goto_line_start"
C-e     = "goto_line_end_newline"
C-h     = ["move_prev_word_end", "move_char_left", "move_char_right"]
C-l     = ["move_next_word_start", "move_char_right"]
C-space = "completion"
esc     = [":set cursorline true", "normal_mode"]

[keys.select]
D = ["yank_to_clipboard", "delete_selection_noyank"]
X = "select_line_above"
y = "yank_to_clipboard"

"+" = "rotate_selection_contents_backward"
"_" = "rotate_selection_contents_forward"

"@" = "@<C-s>*%s<up><ret>"

[keys.normal]
Z = "no_op"

"@" = "@<C-s>*%s<up><ret>"

A-left  = ["move_prev_word_end", "move_char_left", "move_char_right"]
A-right = ["move_next_word_start", "move_char_right"]
C-d     = ["half_page_down", "align_view_center"]
C-h     = ["move_prev_word_end", "move_char_left", "move_char_right"]
C-l     = ["move_next_word_start", "move_char_right"]
C-u     = ["half_page_up", "align_view_center"]

"+" = "expand_selection"
X   = "extend_line_above"
"_" = "shrink_selection"

D = ["yank_to_clipboard", "delete_selection_noyank"]
Y = ["extend_to_line_end", "yank_to_clipboard"]

P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
d = ["delete_selection_noyank"]
p = "paste_clipboard_after"
y = "yank_to_clipboard"

A = [":set cursorline false", "insert_at_line_end"]
I = [":set cursorline false", "insert_at_line_start"]
O = [":set cursorline false", "open_above"]
c = [":set cursorline false", "change_selection"]
i = [":set cursorline false", "insert_mode"]
o = [":set cursorline false", "open_below"]


"{" = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "align_view_center",
]
"}" = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "align_view_center",
]

C-t = [
  ":sh rm -f -- /tmp/yazi-helix",
  ":insert-output yazi --chooser-file=/tmp/yazi-helix -- '%{buffer_name}'",
  ':insert-output printf -- %s "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ":open %sh{cat -- /tmp/yazi-helix}",
  ":set mouse false",
  ":set mouse true",
  ":redraw",
]

[keys.normal.space]
Y = "no_op"
m = ":format"
p = "no_op"

P = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":set mouse false",
  ":set mouse true",
  ":redraw",
  ":reload-all",
]

[keys.normal.space.y]
f = ":toggle cursorcolumn"
l = ":toggle lsp.display-inlay-hints"
y = ":toggle search.smart-case"

i = ":toggle inline-diagnostics.other-lines disable hint"
o = ":toggle inline-diagnostics.cursor-line disable hint"

[keys.normal.'\']
D = ':reset-diff-change'
Q = ":write-quit-all!"
R = ":config-reload"
r = ":reload-all"
t = "vsplit"
w = "wclose"
x = ":buffer-close!"
