Go = {}

require("go.checktime")
require("go.clipboard")
require("go.commands")
require("go.cursor")
require("go.keymap")
require("go.lsp")
require("go.operators.casing")
require("go.operators.replace")
require("go.operators.search")
require("go.opts")
require("go.paths")
require("go.plugins")
require("go.search")
require("go.session")
require("go.status_line")
require("go.text_objects.entire")
require("go.text_objects.indent")
require("go.text_objects.line")
require("go.text_objects.move")
require("go.text_objects.sort")
require("go.theme")
require("go.whitespace")
