Go = {}

require("go.bookmark")
require("go.checktime")
require("go.clipboard")
require("go.commands")
require("go.cursor")
require("go.cwd")
require("go.fmt")
require("go.keymap")
require("go.lsp")
require("go.misc")
require("go.operators.casing")
require("go.operators.move")
require("go.operators.replace")
require("go.operators.search")
require("go.operators.sort")
require("go.opts")
require("go.paths")
require("go.plugins")
require("go.search")
require("go.status_line")
require("go.terminal")
require("go.text_objects.entire")
require("go.text_objects.indent")
require("go.text_objects.line")
require("go.theme")
require("go.treesitter")
require("go.undo")
require("go.whitespace")
require("go.windows")
require("go.yazi")

--
require("go.pack")
require("go.session")
