# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
---
version: 2
final_space: true
transient_prompt:
  template: "\u276F "
secondary_prompt:
  template: &prompt "\u276F"

console_title_template: |-
  {{ if or (eq .PWD .Env.HOME) (eq .PWD "~") }}~{{ else }}@{{ .Folder }}{{ end }}

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: plain
        template: "\ue5ff <lightBlue>{{ .Parent }}</>{{ if or (eq .PWD .Env.HOME) (eq .PWD \"~\") }}~{{ else }}{{ .Folder }}{{ end }}"
        foreground: blue
        properties:
          style: agnoster_full

      - type: git
        style: plain
        foreground: green
        properties:
          fetch_status: True
          fetch_stash_count: True
          fetch_upstream_icon: True

  - type: prompt
    alignment: right
    segments:
      - type: executiontime
        style: plain
        foreground: yellow
        properties:
          threshold: 99

      # - type: project
      #   style: plain
      #   foreground: darkGray

      # - type: java
      #   style: diamond
      #   trailing_diamond: "<#b07219></>"
      #   foreground: "#b07219"

      # - type: dotnet
      #   style: diamond
      #   trailing_diamond: "<#b845fc></>"
      #   foreground: "#b845fc"

      # - type: npm
      #   style: diamond
      #   trailing_diamond: "<#f1e05a></>"
      #   foreground: "#f1e05a"

      # - type: node
      #   style: diamond
      #   trailing_diamond: "<#f1e05a></>"
      #   foreground: "#f1e05a"

      # - type: ruby
      #   style: diamond
      #   trailing_diamond: "<#701516></>"
      #   foreground: "#701516"

      - type: python
        style: diamond
        trailing_diamond: "<#3572A5></>"
        foreground: "#3572A5"

      # - type: r
      #   style: diamond
      #   trailing_diamond: "<#358a5b>ﳒ</>"
      #   foreground: "#358a5b"

      # - type: julia
      #   style: diamond
      #   trailing_diamond: "<#a270ba></>"
      #   foreground: "#a270ba"

      # - type: go
      #   style: diamond
      #   trailing_diamond: "<#00ADD8></>"
      #   foreground: "#00ADD8"

      # - type: rust
      #   style: diamond
      #   trailing_diamond: "<#dea584></>"
      #   foreground: "#dea584"

      # - type: haskell
      #   style: diamond
      #   trailing_diamond: "<#5e5086></>"
      #   foreground: "#5e5086"

      - type: text
        style: plain
        template: "<u> </u>"

      - type: status
        style: plain
        template: "{{ if .Error }}<red>\uf00d <b>{{ .Meaning }}</b></>{{ else }}<green>\uf42e</>{{ end }} "
        properties:
          always_enabled: True

      - type: session
        style: plain
        template: "{{ if .SSHSession }}{{ .UserName }}@{{ .HostName }}{{ end }} "
        foreground: black

      # - type: time
      #   style: plain
      #   foreground: darkGray
      #   template: "<u>{{ .CurrentDate | date .Format }}</u>"
      #   properties:
      #     time_format: "15:04:05 MST"

      - type: shell
        style: plain
        foreground: red

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground: green
        template: *prompt

  - type: rprompt
    segments:
      - type: text
        style: plain
        template: " ["
        foreground: &bracketColour darkGray

      - type: root
        style: plain
        template: " !!"
        foreground: lightRed

      - type: os
        style: plain
        foreground: darkGray

      - type: text
        style: plain
        template: "] "
        foreground: *bracketColour

      - type: text
        style: plain
        template: "\u276E"
        foreground: green
