---
git:
  paging:
    pager: delta --24-bit-color=never

gui:
  scrollHeight: 1
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    lightTheme: True
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
