###

unmap =
unmap F
unmap I
unmap t

###

map <right> eval fm.move(right=1) if fm.thisfile and fm.thisfile.is_directory else None
map l       eval fm.move(right=1) if fm.thisfile and fm.thisfile.is_directory else None

map D delete
map d delete # trash is broken in old versions
map p paste
map P paste overwrite=True
map x cut
map X uncut
map y copy
map Y uncut

map <esc> chain change_mode normal; mark_files all=True val=False; filter; filter_stack clear
map f     console filter%space
map r     rename_append
map v     toggle_visual_mode

map ex shell -- chmod -- +x %s
map eX shell -- chmod -- -x %s

###


# YAZI 2 #
# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

map g<Space> console cd%space
map gc       cd ~/.config
map gd       cd ~/Downloads
map gg       move to=0
map gh       cd ~
map gT       cd $XDG_DATA_HOME/ranger/trash

map mm linemode mtime
map mn linemode filename
map mp linemode permissions
map ms linemode sizehumanreadablemtime

map cc yank path
map cd yank dir
map cf yank name
map cn yank name_without_extension
map cr shell -- ~/.config/yazi/libexec/copy-relative.sh %f
map cl paste_symlink relative=True

map ,a chain set sort=basename;  set sort_reverse=False
map ,A chain set sort=basename;  set sort_reverse=True
map ,e chain set sort=extension; set sort_reverse=False
map ,E chain set sort=extension; set sort_reverse=True
map ,m chain set sort=mtime;     set sort_reverse=False; linemode mtime
map ,M chain set sort=mtime;     set sort_reverse=True;  linemode mtime
map ,n chain set sort=natural;   set sort_reverse=False
map ,N chain set sort=natural;   set sort_reverse=True
map ,r set sort=random
map ,s chain set sort=size;      set sort_reverse=False; linemode sizehumanreadablemtime
map ,S chain set sort=size;      set sort_reverse=True;  linemode sizehumanreadablemtime

map a  console touch%space
map A  console mkdir%space
map q  quitall
map tt tab_new

# YAZI 2 #
