# https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf

set cd_tab_fuzzy                true
set clear_filters_on_dir_change true
set confirm_on_delete           always
set draw_borders                both
set preview_images              true
set scroll_offset               3
set show_hidden                 true
set sort_unicode                true
set tilde_in_titlebar           true
set unicode_ellipsis            true
set wrap_scroll                 true
