set cd_tab_fuzzy      true
set draw_borders      both
set preview_images    true
set save_tabs_on_exit true
set short_unicode     true
set show_hidden       true
set tilde_in_titlebar true
set unicode_ellipsis  true
set wrap_scroll       true
