# https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf

set cd_tab_fuzzy                true
set clear_filters_on_dir_change true
set draw_borders                both
set preview_images              true
set save_tabs_on_exit           true
set sort_unicode                true
set show_hidden                 true
set tilde_in_titlebar           true
set unicode_ellipsis            true
set wrap_scroll                 true

map <right> eval fm.move(right=1) if fm.thisfile and fm.thisfile.is_directory else None
map l       eval fm.move(right=1) if fm.thisfile and fm.thisfile.is_directory else None

map zf console find%space
map f  console filter%space
