#

set-hook -g -a pane-focus-in   "set-option -t '' -p window-style default"
set-hook -g -a pane-focus-in   "set-option -t '' -w window-status-style default"
set-hook -g -a session-created "run-shell -b $tmux_bin_dir/saved.sh"
