#

set-hook -g -a pane-focus-in  "set-option -t '' -p window-style default"
set-hook -g -a pane-died      "run-shell -b $tmux_bin_dir/save.sh"
set-hook -g -a pane-exited    "run-shell -b $tmux_bin_dir/save.sh"
set-hook -g -a pane-focus-in  "run-shell -b $tmux_bin_dir/save.sh"
set-hook -g -a pane-focus-out "run-shell -b $tmux_bin_dir/save.sh"
set-hook -g -a pane-focus-in  "run-shell -b $tmux_bin_dir/saved.sh"
