#################### ############# ####################
#################### Nested Region ####################
#################### ############# ####################

%if "#{==:#{__TMUX_ROOT_SOCKET__},}"
run-shell "tmux set-environment -g __TMUX_ROOT_SOCKET__ #{socket_path}"
%elif "#{!=:#{__TMUX_ROOT_SOCKET__},#{socket_path}}"
run-shell 'test -n "$__TMUX_ROOT_PANE__" || tmux set-environment -g __TMUX_ROOT_PANE__ "#{TMUX_PANE}"'
%endif

## Toggle leader key

bind-key -T root C-\\ \
  set prefix None \;\
  set prefix2 None \;\
  set key-table off \;\
  set status-bg "$tmux_colour_mask" \;\
  refresh-client -S


bind-key -T off C-\\ \
  set -u prefix \;\
  set -u prefix2 \;\
  set -u key-table \;\
  set -u status-bg \;\
  refresh-client -S
