#cloud-config
---
bootcmd:
  - - cloud-init-per
    - once
    - uuid-0
    - date
    - "--set=${DATE}"
users:
  - name: root
    lock_passwd: false
    hashed_passwd: ${PASSWD}
    ssh_authorized_keys: ${AUTHORIZED_KEYS}
