#cloud-config
---
growpart:
  ignore_growroot_disabled: false

hostname: ${HOSTNAME}

write_files:
  - path: /etc/cloud/cloud.cfg.d/99-custom-networking.cfg
    content: |
      network: {config: disabled}

  - path: /usr/local/lib/systemd/network/00-cloud-init.network
    content: |
      [Match]
      Name                = e*

      [Network]
      DHCP                = yes
      LinkLocalAddressing = yes
      LLDP                = yes
      EmitLLDP            = customer-bridge

runcmd:
  - - rm
    - -rf
    - --
    - /etc/netplan
  - - networkctl
    - reload

users:
  - name: root
    lock_passwd: false
    hashed_passwd: ${PASSWD}
    ssh_authorized_keys: ${AUTHORIZED_KEYS}
