---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: ${{ secrets.DOCKER_USERNAME }}/cli
      #     tags: latest
      #     dockerfile: "docker/posix/Dockerfile"

      - run: |-
          make build

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          # make lint
          ./main.sh localhost
          # make fmt
          git diff --exit-code

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          sudo -- mkdir -p -- /opt/homebrew/bin
          sudo -- ln -sf -- /bin/sh /opt/homebrew/bin/dash
          brew install -- bash make
          rm -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

      - run: |-
          ./main.sh localhost

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          # ./main.sh localhost
          true
