---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  # docker:
  #   strategy:
  #     matrix:
  #       platform:
  #         - ubuntu-latest
  #         # - windows-latest

  #   runs-on: ${{ matrix.platform }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     # - uses: docker/build-push-action@v1
  #     #   with:
  #     #     username: ${{ secrets.DOCKER_USERNAME }}
  #     #     password: ${{ secrets.DOCKER_PASSWORD }}
  #     #     repository: ${{ secrets.DOCKER_USERNAME }}/cli
  #     #     tags: latest
  #     #     dockerfile: "docker/posix/Dockerfile"

  #     - shell: bash
  #       run: |-
  #         gmake build

  # ubuntu:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         ./main.sh localhost

  #     - run: |-
  #         gmake fmt
  #         git diff --exit-code

  # macos:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         brew install -- bash make
  #         rm -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         ./main.sh localhost

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          powershell ./layers/nt/winget.ps1

      - shell: bash
        run: |-
          # winget install --exact --id BurntSushi.ripgrep.MSVC
          TMP="$(mktemp)"
          winget export --disable-interactivity --accept-source-agreements --output "$TMP"
          cat -- "$TMP"

      - shell: bash
        run: |-
          # ./main.sh localhost
          true
