---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  # docker:
  #   strategy:
  #     matrix:
  #       platform:
  #         - ubuntu-latest
  #         # - windows-latest

  #   runs-on: ${{ matrix.platform }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - shell: bash
  #       run: |-
  #         gmake build

  # ubuntu:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         ./main.sh localhost

  #     - run: |-
  #         gmake fmt
  #         git diff --exit-code

  # macos:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         brew install -- bash make gnu-getopt
  #         rm -v -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         BREW="$(brew --prefix)"
  #         PATH="$BREW/opt/gnu-getopt/bin:$PATH" ./main.sh localhost

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          powershell ./layers/nt/winget.ps1

      - run: |-
          $TMP = 'wg.json'
          winget export --disable-interactivity --accept-source-agreements --output $TMP
          Get-Content -- $TMP

      - shell: bash
        run: |-
          rm -v -f -- "$HOMEPATH/.local/share"
          choco install -- rsync

      - shell: bash
        run: |-
          ./main.sh localhost
