---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Base
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/cli
          tags: base
          dockerfile: "docker/base/Dockerfile"

      - name: Build Full
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/cli
          tags: full
          dockerfile: "docker/full/Dockerfile"

  unix:
    strategy:
      matrix:
        env:
          - os: ubuntu-latest
            playbook: local.ubuntu.yml
          - os: macos-latest
            playbook: local.macos.yml

    runs-on: ${{ matrix.env.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |-
          pip3 install -- ansible

      - name: Build
        run: |-
          sudo ansible-playbook '${{ matrix.env.playbook }}' -e all=true

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Msys2
        uses: msys2/setup-msys2@v2

      - name: Ensure openssh
        run: |-
          C:\\msys64\usr\bin\pacman.exe --sync --needed --noconfirm -- openssh

      # - name: Run Ansible
      #   shell: bash
      #   run: |-
      #     ./docker/nt/build.sh
