---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Base
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/cli
          tags: base
          dockerfile: "docker/base/Dockerfile"

      - name: Build Full
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/cli
          tags: full
          dockerfile: "docker/full/Dockerfile"

  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ansible
        run: pip3 install -- ansible

      - name: Build
        run: ansible-playbook local.macos.yml -e all=true

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable SSHd
        run: |-
          Add-WindowsCapability -Name 'OpenSSH.Server'
          Set-Service -Name 'sshd' -Status 'Running'

  #     - name: Install Ansible
  #       run: |-
  #         $pacman Join-Path $Env:SystemDrive 'msys64' 'usr' 'bin' 'pacman.exe'
  #         $pacman --sync --needed --noconfirm -- 'ansible'
  #         Get-ChildItem env:

  #     - name: Build
  #       run: |-
  #         $inventory = @"
  #         [localwindows]
  #         administrator@127.0.0.1
  #         "@
  #         $inventory | Out-File 'inventory.ni'
  #         ansible-playbook local.windows.yml -e all=true
