---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          # - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |-
          gmake build

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          env | sort -t = -k 1

      - run: |-
          gmake lint

      - run: |-
          unset -- PIPX_HOME
          ./main.sh localhost

      - run: |-
          unset -- PIPX_HOME
          ./main.sh localhost -- --debug

      - run: |-
          gmake fmt
          git diff --exit-code

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          env | sort -t = -k 1

      - run: |-
          brew install -- bash make gnu-getopt coreutils
          rm -v -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

      - run: |-
          gmake lint

      - run: |-
          PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          unset -- PIPX_HOME
          ./main.sh localhost

      - run: |-
          PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          unset -- PIPX_HOME
          ./main.sh localhost -- --debug

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          Get-ChildItem Env:* | Sort-Object Name

          Get-Command -All -- bash
          Get-Command -All -- cygpath
          Get-Command -All -- gmake
          Get-Command -All -- nproc
          Get-Command -All -- python3
          Get-Command -All -- sh
          Get-Command -All -- tar
          Get-Command -All -- unzip

      - run: |-
          Get-ChildItem -Force -- (Join-Path -Path $Env:ProgramFiles 'Git')

      - run: |-
          $pacman = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'pacman'
          $argv = @('--sync', '--refresh', '--noconfirm', '--', 'rsync', 'make')
          & $pacman @argv

      - run: |-
          & powershell .\layers\nt\winget.ps1

      - run: |-
          Get-Command -All -- winget

      - run: |-
          $bin = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin'
          $Env:GMAKE = Join-Path -Path $bin 'make'
          $Env:RSYNC = Join-Path -Path $bin 'rsync'
          $Env:PIPX_HOME = ''

          bash .\main.sh localhost

      - run: |-
          $bin = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin'
          $Env:GMAKE = Join-Path -Path $bin 'make'
          $Env:RSYNC = Join-Path -Path $bin 'rsync'
          $Env:PIPX_HOME = ''

          bash .\main.sh localhost -- --debug

      - run: |-
          $tmp = 'out.json'
          & 'winget' 'export' '--disable-interactivity' '--accept-source-agreements' '--output' $tmp
          Get-Content -Path $tmp
