---
on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  formulae:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - run: |-
          HOMEBREW_DEVELOPER=1 brew install --HEAD --formula -- ./formulae/*
          HOMEBREW_DEVELOPER=1 brew reinstall --formula -- ./formulae/*

  docker:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          # TODO: windows?
          # - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v5

      - shell: bash
        run: |-
          gmake build

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: "25"

      - run: |-
          curl --disable --fail --location --no-progress-meter -- 'https://raw.githubusercontent.com/ms-jpq/deb/refs/heads/deb/pubkey.asc' | sudo -- gpg --batch --dearmor --yes --output /etc/apt/trusted.gpg.d/ms-jpq.gpg
          sudo -- tee -- /etc/apt/sources.list.d/ms-jpq.list <<-'EOF'
          deb https://raw.githubusercontent.com/ms-jpq/deb/refs/heads/deb/ /
          EOF

      - run: |-
          sudo -- apt-get update
          sudo -- apt-get install --no-install-recommends --yes -- swi-prolog-nox gnucobol moreutils libarchive-tools neovim
          sudo -- apt purge --yes -- firefox

      - run: |-
          /home/linuxbrew/.linuxbrew/bin/brew install -- clojure/tools/clojure
          eval -- "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          CLJ="$(command -v -- clojure)"
          sudo -- ln -v -sTnfr -- "$CLJ" /usr/local/bin/clojure
          mkdir -p ~/.config/clojure/.cpcache

      - run: |-
          gmake lint

      - run: |-
          ./main.sh localhost -- all helix

      - run: |-
          ./main.sh localhost -- --debug

      - run: |-
          gmake fmt
          git diff --exit-code

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: "25"

      - run: |-
          brew install -- bash make gnu-getopt coreutils neovim
          rm -v -fr -- "$HOME"/{.config,.cache} "$HOME/.local"/{share,state}
          mkdir -p ~/.config/clojure/.cpcache

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake lint

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          ./main.sh localhost -- all helix

      - run: |-
          PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          ./main.sh localhost -- --debug

  windows:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5

      - uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: "25"

      - run: |-
          winget.exe install '--disable-interactivity' '--accept-source-agreements' '--accept-package-agreements' '--exact' '--id' 'ezwinports.make'

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)
          Get-Command -All -- bash
          Get-Command -All -- make
          Get-Command -All -- npm

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)

          bash .\win.sh localhost -- all helix JAVA_HOME="$Env:JAVA_HOME_21_X64"

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)

          bash .\win.sh localhost -- '--debug'
