---
on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  docker:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: |-
          gmake build

  ubuntu:
    # TODO: use ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - run: |-
          env | sort -t = -k 1

      - run: |-
          gmake lint

      - run: |-
          ./main.sh localhost --

      - run: |-
          ./main.sh localhost -- --debug

      - run: |-
          gmake fmt
          git diff --exit-code

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - run: |-
          env | sort -t = -k 1

      - run: |-
          brew install -- bash make gnu-getopt coreutils
          rm -v -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          gmake lint

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          ./main.sh localhost --

      - run: |-
          PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
          ./main.sh localhost -- --debug

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |-
          # TODO: https://github.com/actions/runner-images/issues/910#issuecomment-2113154618
          powershell.exe .\layers\nt\winget.ps1

      - run: |-
          winget.exe install '--disable-interactivity' '--accept-source-agreements' '--accept-package-agreements' '--exact' '--id' 'ezwinports.make'

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)
          Get-Command -All -- bash
          Get-Command -All -- make

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)

          bash .\win.sh localhost --

      - run: |-
          $Env:Path = @((Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WinGet' 'Links'), $Env:Path) | Join-String -Separator ([IO.Path]::PathSeparator)

          bash .\win.sh localhost -- '--debug'

      - run: |-
          $tmp = 'out.json'
          winget export '--disable-interactivity' '--accept-source-agreements' '--output' $tmp
          Get-Content -Path $tmp
