---
name: CI

on:
  push:
    branches:
      - wang
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  # docker:
  #   strategy:
  #     matrix:
  #       platform:
  #         - ubuntu-latest
  #         # - windows-latest

  #   runs-on: ${{ matrix.platform }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - shell: bash
  #       run: |-
  #         gmake build

  # ubuntu:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         env | sort -t = -k 1

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         unset -- PIPX_HOME
  #         ./main.sh localhost

  #     - run: |-
  #         unset -- PIPX_HOME
  #         ./main.sh localhost -- --debug

  #     - run: |-
  #         gmake fmt
  #         git diff --exit-code

  # macos:
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - run: |-
  #         env | sort -t = -k 1

  #     - run: |-
  #         brew install -- bash make gnu-getopt
  #         rm -v -fr -- "$HOME/.config" "$HOME/.cache" "$HOME/.local/share"

  #     - run: |-
  #         gmake lint

  #     - run: |-
  #         PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
  #         unset -- PIPX_HOME
  #         ./main.sh localhost

  #     - run: |-
  #         PATH="$(brew --prefix)/opt/gnu-getopt/bin:$PATH"
  #         unset -- PIPX_HOME
  #         ./main.sh localhost -- --debug

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          Get-ChildItem Env:* | Sort-Object Name

          Get-Command -- bash
          Get-Command -- cygpath
          Get-Command -- gmake
          Get-Command -- python3
          Get-Command -- sh
          Get-Command -- tar
          Get-Command -- unzip

          Get-ChildItem -Force $Env:ProgramFiles
          Get-ChildItem -Force ${Env:ProgramFiles(x86)}

      - run: |-
          $pacman = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'pacman'
          $argv = @('--sync', '--refresh', '--noconfirm', '--', 'rsync')
          & $pacman @argv

      - run: |-
          & powershell './layers/nt/winget.ps1'

      - run: |-
          $winget = Join-Path -Path $Env:LOCALAPPDATA 'Microsoft' 'WindowsApps' 'winget'
          $argv = @('install', '--disable-interactivity', '--accept-source-agreements', '--accept-package-agreements', '--exact', '--id', 'GnuWin32.Make')
          & $winget @argv

      - run: |-
          Get-Command -- make
          Get-Command -- gmake

          Get-ChildItem -Force $Env:ProgramFiles
          Get-ChildItem -Force ${Env:ProgramFiles(x86)}

          Get-Command -- winget

      - run: |-
          $Env:RSYNC_EXE = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'rsync'
          $Env:PIPX_HOME = ''
          $make = Join-Path -Path ${Env:ProgramFiles(x86)} 'GnuWin32' 'bin' 'make'
          & $make 'localhost'

      - run: |-
          $Env:RSYNC_EXE = Join-Path -Path $Env:GHCUP_MSYS2 'usr' 'bin' 'rsync'
          $Env:PIPX_HOME = ''
          gmake 'localhost' ARGV='-- --debug'

      - run: |-
          $tmp = 'out.json'
          & 'winget' 'export' '--disable-interactivity' '--accept-source-agreements' '--output' $tmp
          Get-Content -Path $tmp
