# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
---
notARepository: quit

os:
  editInTerminal: false
  edit: ~/.local/bin/tmux-edit -- {{filename}}
  editAtLine: ~/.local/bin/tmux-edit +{{line}} -- {{filename}}
  openDirInEditor: ~/.local/bin/tmux-edit -- {{dir}}
  open: ~/.local/bin/tmux-edit -- {{filename}}
  openLink: $BROWSER {{link}}

git:
  ignoreWhitespaceInDiffView: true
  overrideGpg: true
  pagers:
    - pager: delta --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - pager: delta --paging=never --hyperlinks-file-link-format="lazygit-edit://{path}:{line}" --side-by-side
    - externalDiffCommand: difft --syntax-highlight=on --color=always

worktree:
  defaultPath: .worktrees

gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  scrollHeight: 1
  shortTimeFormat: 15:04
  showRootItemInFileTree: false
  tabWidth: 2
  timeFormat: 2006-01-02

  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
