# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
---
git:
  overrideGpg: true
  pagers:
    - pager: delta --paging=never --24-bit-color=never
notARepository: quit

os:
  editInTerminal: false
  edit: ~/.local/bin/tmux-edit -- {{filename}}
  editAtLine: ~/.local/bin/tmux-edit +{{line}} -- {{filename}}
  openDirInEditor: ~/.local/bin/tmux-edit -- {{dir}}
  openLink: $BROWSER {{link}}

gui:
  scrollHeight: 1
  theme:
    activeBorderColor:
      - blue
    inactiveBorderColor:
      - black
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
